version: '3.7'

services:
  postgres:
    container_name: saas-template-pg
    image: postgres:latest
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-saas-template-pg}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped

  pgadmin:
    container_name: saas-template-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    restart: unless-stopped

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
