name: Deploy to Vercel on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .vercel directory
        run: mkdir -p .vercel

      - name: Create project.json file from secret
        run: echo '${{ secrets.VERCEL_PROJECT_CONFIG }}' > .vercel/project.json

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel in background
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: nohup vercel --token $VERCEL_TOKEN --prod &
